In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 4.2 MB/s eta 0:00:03
   --- ------------------------------------ 1.0/12.6 MB 2.3 MB/s eta 0:00:06
   ---- ----------------------------------- 1.3/12.6 MB 2.3 MB/s eta 0:00:05
   ---- ----------------------------------- 1.6/12.6 MB 2.2 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.6 MB 1.8 MB/s eta 0:00:06
   ------- -------------------------------- 2.4/12.6 MB 1.8 MB/s eta 0:00:06
   -------- ------------------------------- 2.6/12.6 MB 1.9 MB/s eta 0:00:06
   --------- ------------------------------ 2.9/12.6 MB 1.7 MB/s eta 0:00:06
   --------- ------------------------------ 2.9/12.6 MB 1.7 MB/s eta 0:00:06
   --------- ------------------------------ 3.1/12.6 MB 1.5 MB/s eta 0:00:07
   -------------- ------------------------- 4.5/12.6 MB 1.9 MB/s eta 0:00:05
   ------------------- -------------------- 6.3/12.6 MB 2.4 MB/s eta 0:00:03
   ---

In [1]:
import numpy as np

In [3]:
import time

In [5]:
import sys

In [27]:
# example demonstrates storage size when comparing python list and numpy array
i = range(1000)
print(sys.getsizeof(555), sys.getsizeof(555)*len(i))
j = np.arange(1000)
print(j.size, j.itemsize, j.size*j.itemsize)


28 28000
1000 8 8000


In [14]:
# example demonstrates time factor when comparing python list and numpy array
size=1000000
i=range(size)
j=range(size)

a=np.arange(size)
b=np.arange(size)

#python list
start=time.time()
result=[(x+y) for x,y in zip(i, j)]
print("python list took: ", (time.time()-start)*1000)

#numpy array
start=time.time()
result=a+b
print("numpy took: ", (time.time()-start)*1000)

python list took:  178.53856086730957
numpy took:  24.005413055419922


In [9]:
np.array([1,2,4])

array([1, 2, 4])

In [17]:
np.array([[1,2,4],[5,6,7]], dtype=float)

array([[1., 2., 4.],
       [5., 6., 7.]])

In [35]:
np.zeros((3,2), dtype=np.int16)

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int16)

In [39]:
np.ones((4, 5), dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [43]:
np.arange(19, 100, 8)

array([19, 27, 35, 43, 51, 59, 67, 75, 83, 91, 99])

In [50]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [35]:
b = np.full((2,3, 4),9)
b

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [68]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [72]:
np.random.random((3,3))

array([[0.34492156, 0.83711903, 0.23178304],
       [0.85668163, 0.67424101, 0.92280757],
       [0.24965919, 0.74714061, 0.3151956 ]])

In [33]:
a = np.empty((2,2))
a

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.10758628e-311]])

In [94]:
np.savez('my_array.npz', a)

In [98]:
np.load('my_array.npy')

array([[1.13483612e+119]])

In [116]:
np.savetxt('my_array.txt', a)

In [118]:
np.loadtxt('my_array.txt')

array([[0.03894171, 0.51183004],
       [0.20305815, 0.72166714]])

In [128]:
np.loadtxt('my_array.txt', delimiter=" ", dtype=int)

C:\Users\e22108.EXTRAMARKS\AppData\Local\Temp\ipykernel_17184\1484095265.py:1: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  np.loadtxt('my_array.txt', delimiter=" ", dtype=int)


array([[0, 0],
       [0, 0]])

In [130]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [132]:
a.shape

(2, 2)

In [138]:
b.shape

(2, 3, 4)

In [140]:
len(a)

2

In [142]:
len(b)

2

In [145]:
a.ndim

2

In [147]:
b.ndim

3

In [149]:
a.size

4

In [151]:
b.size

24

In [153]:
b.dtype

dtype('int64')

In [155]:
a.dtype

dtype('float64')

In [157]:
a.dtype.name

'float64'

In [37]:
b.astype(np.int32)
b.dtype

dtype('int64')

In [171]:
b.dtype

dtype('int64')

In [175]:
np.array_equal(a, b)

False

In [213]:
# array wise comparison
np.array_equal(np.array([1,1]), np.array([1,2]))

False

In [39]:
# Element wise comparison
np.array([1,2]) == np.array([2,2])

array([False,  True])

In [229]:
a < 2

array([[ True,  True],
       [ True,  True]])

In [187]:
np.add(np.array([1,1]), np.array([1,2]))

array([2, 3])

In [189]:
np.array([1,1]) + np.array([1,2])

array([2, 3])

In [195]:
np.subtract(np.array([1,1]), np.array([1,2]))

array([ 0, -1])

In [197]:
np.array([1,1]) - np.array([1,2])

array([ 0, -1])

In [199]:
np.multiply(np.array([1,1]), np.array([1,2]))

array([1, 2])

In [201]:
np.array([1,1]) * np.array([1,2])

array([1, 2])

In [203]:
np.exp(b)

array([[[8103.08392758, 8103.08392758, 8103.08392758, 8103.08392758],
        [8103.08392758, 8103.08392758, 8103.08392758, 8103.08392758],
        [8103.08392758, 8103.08392758, 8103.08392758, 8103.08392758]],

       [[8103.08392758, 8103.08392758, 8103.08392758, 8103.08392758],
        [8103.08392758, 8103.08392758, 8103.08392758, 8103.08392758],
        [8103.08392758, 8103.08392758, 8103.08392758, 8103.08392758]]])

In [205]:
[1,2,3]+[4]

[1, 2, 3, 4]

In [207]:
np.add([1,2,3], [4])

array([5, 6, 7])

In [235]:
b.sum()

np.int64(216)

In [237]:
a.min()

np.float64(0.03894171102542143)

In [239]:
a.max()

np.float64(0.7216671366994956)

In [247]:
a.max(axis=1)

array([0.51183004, 0.72166714])

In [243]:
a

array([[0.03894171, 0.51183004],
       [0.20305815, 0.72166714]])

In [249]:
a.cumsum()

array([0.03894171, 0.55077175, 0.7538299 , 1.47549703])

In [251]:
a.sum()

np.float64(1.4754970343845917)

In [253]:
a.cumsum(axis=0)

array([[0.03894171, 0.51183004],
       [0.24199986, 1.23349717]])

In [41]:
a.mean()

np.float64(6.953902120063161e-307)

In [43]:
np.median(b)

np.float64(9.0)

In [45]:
np.median(a)

np.float64(5.451694083955082e-307)

In [47]:
np.std(a)

np.float64(0.0)

In [61]:
np.std(np.array([1,2,3,4]))

np.float64(1.118033988749895)

In [59]:
np.corrcoef(np.array([1,2,3,4]))

np.float64(1.0)

In [57]:
np.corrcoef(np.array([1,2,3,4]))

np.float64(1.0)