In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_digits

In [2]:
digits_data = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits_data.data, digits_data.target, test_size=0.2)

In [3]:
model_lr = LogisticRegression(solver='liblinear')
model_lr.fit(X_train, y_train)
model_lr.score(X_test, y_test)

0.9472222222222222

In [4]:
model_svm = SVC(gamma='auto')
model_svm.fit(X_train, y_train)
model_svm.score(X_test, y_test)

0.5333333333333333

In [5]:
model_rf = RandomForestClassifier(n_estimators=50)
model_rf.fit(X_train, y_train)
model_rf.score(X_test, y_test)

0.9638888888888889

In [6]:
kf = KFold(n_splits=3)

In [7]:
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9,0]):
    print(train_index, test_index)

[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


In [9]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)
    

In [33]:
skfold = StratifiedKFold(n_splits=3)
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in skfold.split(digits_data.data, digits_data.target):
    X_train, X_test, y_train, y_test = digits_data.data[train_index], digits_data.data[test_index], \
                                        digits_data.target[train_index], digits_data.target[test_index]
    scores_lr.append(get_score(LogisticRegression(solver='liblinear'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=50), X_train, X_test, y_train, y_test))

In [35]:
scores_lr

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [37]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [39]:
scores_rf

[0.9298831385642737, 0.9549248747913188, 0.9198664440734557]

In [69]:
cross_val_score(LogisticRegression(solver='liblinear'), digits_data.data, digits_data.target, cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [71]:
cross_val_score(SVC(gamma='auto'), digits_data.data, digits_data.target, cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [73]:
cross_val_score(RandomForestClassifier(n_estimators=50), digits_data.data, digits_data.target, cv=3)

array([0.93989983, 0.94657763, 0.92487479])

In [75]:
s1 = cross_val_score(RandomForestClassifier(n_estimators=50), digits_data.data, digits_data.target, cv=3)
np.average(s1)

np.float64(0.9376739009460211)

In [85]:
s2 = cross_val_score(RandomForestClassifier(n_estimators=20), digits_data.data, digits_data.target, cv=10)
np.average(s2)

np.float64(0.9360148975791434)

In [87]:
s3 = cross_val_score(RandomForestClassifier(n_estimators=10), digits_data.data, digits_data.target, cv=10)
np.average(s3)

np.float64(0.917635009310987)